package App.View;

import App.Controller.OCRController;
import java.io.File;

/**
 *
 * @author Frederick A. Aaron
 */
public class OCRGUI extends javax.swing.JFrame
{
    OCRController parentController;
    File picFile;

    /**
     * Creates new form OCRGUI
     */
    public OCRGUI()
    {
        initComponents();
    }

    public OCRGUI(OCRController parentController)
    {
        this.parentController = parentController;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        radEnglish = new javax.swing.JRadioButton();
        radPolish = new javax.swing.JRadioButton();
        radSpanish = new javax.swing.JRadioButton();
        btnScan = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextArea();
        btnLoad = new javax.swing.JButton();
        txtFileLoaded = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        radEnglish.setSelected(true);
        radEnglish.setText("English");

        radPolish.setText("Polish");

        radSpanish.setText("Spanish");

        btnScan.setText("Scan");
        btnScan.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnScanActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelActionPerformed(evt);
            }
        });

        txtOutput.setColumns(20);
        txtOutput.setLineWrap(true);
        txtOutput.setRows(5);
        txtOutput.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtOutput);

        btnLoad.setText("Load");
        btnLoad.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnLoadActionPerformed(evt);
            }
        });

        txtFileLoaded.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnScan)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCancel)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radSpanish)
                            .addComponent(radPolish)
                            .addComponent(radEnglish)
                            .addComponent(btnLoad))
                        .addGap(28, 28, 28))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(txtFileLoaded, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radEnglish)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(radPolish)
                        .addGap(18, 18, 18)
                        .addComponent(radSpanish)
                        .addGap(34, 34, 34)
                        .addComponent(btnLoad)
                        .addGap(16, 16, 16)
                        .addComponent(txtFileLoaded, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnScan)
                    .addComponent(btnCancel))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelActionPerformed
    {//GEN-HEADEREND:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnLoadActionPerformed
    {//GEN-HEADEREND:event_btnLoadActionPerformed
        picFile = parentController.selectFile();
        txtFileLoaded.setText(picFile.getAbsolutePath());
    }//GEN-LAST:event_btnLoadActionPerformed

    private void btnScanActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnScanActionPerformed
    {//GEN-HEADEREND:event_btnScanActionPerformed
        txtOutput.setText(parentController.scan(picFile));
    }//GEN-LAST:event_btnScanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(OCRGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(OCRGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(OCRGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(OCRGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new OCRGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnScan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radEnglish;
    private javax.swing.JRadioButton radPolish;
    private javax.swing.JRadioButton radSpanish;
    private javax.swing.JTextField txtFileLoaded;
    private javax.swing.JTextArea txtOutput;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnCancel()
    {
        return btnCancel;
    }

    public void setBtnCancel(javax.swing.JButton btnCancel)
    {
        this.btnCancel = btnCancel;
    }

    public javax.swing.JButton getBtnLoad()
    {
        return btnLoad;
    }

    public void setBtnLoad(javax.swing.JButton btnLoad)
    {
        this.btnLoad = btnLoad;
    }

    public javax.swing.JButton getBtnScan()
    {
        return btnScan;
    }

    public void setBtnScan(javax.swing.JButton btnScan)
    {
        this.btnScan = btnScan;
    }

    public javax.swing.JPanel getjPanel1()
    {
        return jPanel1;
    }

    public void setjPanel1(javax.swing.JPanel jPanel1)
    {
        this.jPanel1 = jPanel1;
    }

    public javax.swing.JScrollPane getjScrollPane1()
    {
        return jScrollPane1;
    }

    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1)
    {
        this.jScrollPane1 = jScrollPane1;
    }

    public javax.swing.JRadioButton getRadEnglish()
    {
        return radEnglish;
    }

    public void setRadEnglish(javax.swing.JRadioButton radEnglish)
    {
        this.radEnglish = radEnglish;
    }

    public javax.swing.JRadioButton getRadPolish()
    {
        return radPolish;
    }

    public void setRadPolish(javax.swing.JRadioButton radPolish)
    {
        this.radPolish = radPolish;
    }

    public javax.swing.JRadioButton getRadSpanish()
    {
        return radSpanish;
    }

    public void setRadSpanish(javax.swing.JRadioButton radSpanish)
    {
        this.radSpanish = radSpanish;
    }

    public javax.swing.JTextArea getTxtOutput()
    {
        return txtOutput;
    }

    public void setTxtOutput(javax.swing.JTextArea txtOutput)
    {
        this.txtOutput = txtOutput;
    }

    public javax.swing.JTextField getTxtFileLoaded()
    {
        return txtFileLoaded;
    }

    public void setTxtFileLoaded(javax.swing.JTextField txtFileLoaded)
    {
        this.txtFileLoaded = txtFileLoaded;
    }
}
